{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  type: ExternalName
  externalName: {{ .externalIP }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
{{- end }}

