apiVersion: v2
name: sonarr
description: Sonarr - TV show PVR
type: application
version: 1.0.0
appVersion: "4.0"
dependencies:
  - name: app-template
    version: 4.6.2
    repository: https://bjw-s-labs.github.io/helm-charts/
