apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "actual-budget.fullname" . }}-data
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "actual-budget.name" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
