apiVersion: v1
kind: Service
metadata:
  name: {{ include "graphite-exporter.fullname" . }}
  labels:
    {{- include "graphite-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: {{ .Values.service.graphitePort }}
      targetPort: graphite
      protocol: TCP
      name: graphite
  selector:
    {{- include "graphite-exporter.selectorLabels" . | nindent 4 }}
