apiVersion: v2
appVersion: v0.7.1
description: A Helm chart for Kubernetes
name: kafka-ui
type: application
version: 0.7.5
dependencies:
  - name: kafka-ui
    repository: https://provectus.github.io/kafka-ui-charts
    version: 0.7.5
