app-template:
  controllers:
    main:
      type: cronjob
      cronjob:
        schedule: "0 4 * * 0"
        concurrencyPolicy: Forbid
        successfulJobsHistory: 1
        failedJobsHistory: 3
      containers:
        main:
          image:
            repository: ghcr.io/recyclarr/recyclarr
            tag: 8.7.0
            pullPolicy: IfNotPresent
          args:
            - sync
          env:
            TZ: America/New_York
          envFrom:
            - secretRef:
                name: recyclarr-secret
          resources:
            requests:
              cpu: 25m
              memory: 128Mi
            limits:
              memory: 512Mi

  service: {}

  ingress: {}

  persistence:
    config:
      enabled: true
      type: emptyDir
      globalMounts:
        - path: /config
    config-file:
      enabled: true
      type: configMap
      name: recyclarr-config
      globalMounts:
        - path: /config/recyclarr.yml
          subPath: recyclarr.yml
          readOnly: true

config:
  sonarrBaseUrl: http://sonarr.media-automation.svc.cluster.local:8989
  radarrBaseUrl: http://radarr.media-automation.svc.cluster.local:7878
