- hosts: home_base
  user: rramirez
  become: true
  become_user: root
  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install necessary packages for AMD GPU support and video acceleration
    apt:
      name:
        - mesa-vulkan-drivers
        - mesa-va-drivers
        - vainfo
        - radeontop
        - ffmpeg  # Optional: to ensure VAAPI is supported in media handling
      state: present

  - name: Verify VAAPI support
    command: vainfo
    register: vainfo_output
    ignore_errors: yes

  - name: Display VAAPI info
    debug:
      var: vainfo_output.stdout
