apiVersion: v1
kind: Service
metadata:
  name: {{ include "backblaze-wine.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "backblaze-wine.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: web
      protocol: TCP
      name: web
  selector:
    {{- include "backblaze-wine.selectorLabels" . | nindent 4 }}
