apiVersion: v1
kind: ConfigMap
metadata:
  name: actual-budget-blueprint
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: blueprint
data:
  actual-budget.yaml: |
    version: 1
    metadata:
      name: actual-budget-forward-auth
    entries:
      - model: authentik_providers_proxy.proxyprovider
        state: present
        identifiers:
          name: actual-budget-provider
        attrs:
          name: actual-budget-provider
          mode: forward_single
          external_host: https://budget.theramirez.casa
          access_token_validity: hours=24
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]

      - model: authentik_core.application
        state: present
        identifiers:
          slug: actual-budget
        attrs:
          name: Actual Budget
          slug: actual-budget
          provider: !Find [authentik_providers_proxy.proxyprovider, [name, actual-budget-provider]]

      - model: authentik_outposts.outpost
        state: present
        identifiers:
          name: authentik Embedded Outpost
        attrs:
          providers:
            - !Find [authentik_providers_proxy.proxyprovider, [name, actual-budget-provider]]
