apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: home-network
  namespace: kgateway-system
spec:
  kube:
    service:
      type: LoadBalancer
      externalTrafficPolicy: Cluster
      extraAnnotations:
        metallb.io/address-pool: home-network
