apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mealie.fullname" . }}-data
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "mealie.name" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
