apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plane.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "plane.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.password | quote }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%d/%s" (.Values.secrets.postgres.user | urlquery) (.Values.secrets.postgres.password | urlquery) .Values.postgres.host (int .Values.postgres.port) .Values.postgres.db | quote }}
  RABBITMQ_DEFAULT_USER: {{ .Values.secrets.rabbitmq.user | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.secrets.rabbitmq.password | quote }}
  RABBITMQ_DEFAULT_VHOST: {{ .Values.rabbitmq.vhost | quote }}
  AMQP_URL: {{ printf "amqp://%s:%s@%s:%d/%s" (.Values.secrets.rabbitmq.user | urlquery) (.Values.secrets.rabbitmq.password | urlquery) .Values.rabbitmq.host (int .Values.rabbitmq.port) .Values.rabbitmq.vhost | quote }}
  SECRET_KEY: {{ .Values.secrets.django.secretKey | quote }}
  LIVE_SERVER_SECRET_KEY: {{ .Values.secrets.live.secretKey | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.seaweedfs.s3AccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.seaweedfs.s3SecretAccessKey | quote }}
