services:
  - name: downloads
    externalIP: 192.168.1.225
    port: 8081
    hostname: downloads.theramirez.casa

  - name: homeflix
    externalIP: 192.168.1.218
    port: 32400
    hostname: homeflix.theramirez.casa

  - name: proxmox-store
    externalIP: 192.168.1.216
    port: 8006
    hostname: store.theramirez.casa

  - name: proxmox-infra
    externalIP: 192.168.1.28
    port: 8006
    hostname: infra.theramirez.casa

  - name: router
    externalIP: 192.168.1.1
    port: 443
    hostname: router.theramirez.casa

  - name: wifi
    externalIP: 192.168.10.25
    port: 80
    hostname: wifi.theramirez.casa

  - name: central-sync
    externalIP: 192.168.1.78
    port: 443
    hostname: central-sync.theramirez.casa
    backendProtocol: HTTP
