apiVersion: v2
name: authentik
description: Authentik identity provider for homelab SSO
type: application
version: 0.1.0
appVersion: 2026.2.2
dependencies:
  - name: authentik
    version: 2026.2.2
    repository: https://charts.goauthentik.io
