apiVersion: v1
kind: ConfigMap
metadata:
  name: recyclarr-config
data:
  recyclarr.yml: |
    sonarr:
      series:
        base_url: {{ .Values.config.sonarrBaseUrl | quote }}
        api_key: !env_var SONARR_API_KEY
        delete_old_custom_formats: true
        quality_profiles:
          - name: WEB-1080p
            trash_id: 72dae194fc92bf828f32cde7744e51a1
            reset_unmatched_scores:
              enabled: true
        custom_formats:
          - trash_ids:
              - 32b367365729d530ca1c124a0b180c64
              - 82d40da2bc6923f41e14394075dd4b03
              - e1a997ddb54e3ecbfe06341ad323c458
              - 06d66ab109d4d2eddb2794d21526d140
            assign_scores_to:
              - name: WEB-1080p

    radarr:
      movies:
        base_url: {{ .Values.config.radarrBaseUrl | quote }}
        api_key: !env_var RADARR_API_KEY
        delete_old_custom_formats: true
        quality_profiles:
          - name: HD Bluray + WEB
            trash_id: d1d67249d3890e49bc12e275d989a7e9
            reset_unmatched_scores:
              enabled: true
        custom_formats:
          - trash_ids:
              - b6832f586342ef70d9c128d40c07b872
              - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5
              - 7357cf5161efbf8c4d5d0c30b4815ee2
              - 5c44f52a8714fdd79bb4d98e2673be1f
            assign_scores_to:
              - name: HD Bluray + WEB
