apiVersion: v1
kind: Service
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    app: {{ include "home-assistant.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8123
  selector:
    app: {{ include "home-assistant.name" . }}
