apiVersion: v2
appVersion: v1.20.2
description: A Helm chart for Kubernetes
name: cert-manager
type: application
version: 1.20.2
dependencies:
  - name: cert-manager
    repository: oci://quay.io/jetstack/charts
    version: v1.20.2
