apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudflared.fullname" . }}-config
  labels:
    app: {{ include "cloudflared.name" . }}
data:
  config.yaml: |
    tunnel: {{ .Values.tunnel.id }}
    credentials-file: /etc/cloudflared/credentials.json
    ingress:
      {{- range .Values.tunnel.ingress }}
      - hostname: {{ .hostname }}
        {{- if .path }}
        path: {{ .path }}
        {{- end }}
        service: {{ .service }}
      {{- end }}
      - service: http_status:404
