apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflared.fullname" . }}-credentials
  labels:
    app: {{ include "cloudflared.name" . }}
type: Opaque
stringData:
  credentials.json: |
    {"AccountTag":"{{ .Values.tunnel.accountId }}","TunnelSecret":"{{ .Values.tunnel.secret }}","TunnelID":"{{ .Values.tunnel.id }}"}
